# Generated by Django 4.2.16 on 2026-02-27 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('REPORT_USER', 'Your post was reported'), ('REPORT_ADMIN', 'New report to review'), ('AI_VIOLATION', 'Content removed by AI'), ('SUSPENSION', 'Account suspended'), ('FOLLOW', 'New follower'), ('REACTION', 'Post reaction'), ('COMMENT', 'New comment'), ('MESSAGE', 'New message'), ('SYSTEM', 'System notification')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='AIViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('POST', 'Post'), ('COMMENT', 'Comment')], max_length=10)),
                ('content_id', models.PositiveIntegerField()),
                ('content_text', models.TextField(blank=True, help_text='Snapshot of the removed content')),
                ('reason', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_taken', models.CharField(choices=[('WARNED', 'Warning issued'), ('SUSPENDED_7', 'Suspended 7 days'), ('SUSPENDED_30', 'Suspended 30 days'), ('BANNED', 'Permanently banned')], max_length=15)),
                ('violation_number', models.PositiveIntegerField(help_text='Violation count at time of flagging')),
                ('is_false_positive', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_violations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
