# Generated by Django 4.2.16 on 2026-02-27 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_communitymoderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, help_text='Community rules displayed to members. One rule per line.'),
        ),
        migrations.AddField(
            model_name='communitymoderator',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='about',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
